// Regenerates src/data/slots.js from the "SortedSubmissionsGroups" sheet.
//
//   npm i -D xlsx
//   node scripts/build-slots.mjs path/to/ALLAcceptedPapersGroups.xlsx
//
// The sheet has no header row. Columns:
//   A id · B authors · C title · D track · E decision · F topic · G group id
//
// Row order is kept exactly as it is in the sheet: slots appear in the order
// their group id is first seen, and papers keep their order inside a slot.
// Nothing is re-sorted.
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const XLSX = createRequire(import.meta.url)("xlsx");

const SHEET = "SortedSubmissionsGroups";
const input = process.argv[2] ?? "ALLAcceptedPapersGroups.xlsx";
const output = process.argv[3] ?? "src/data/slots.js";

const sheet = XLSX.readFile(input).Sheets[SHEET];
if (!sheet) throw new Error(`Sheet "${SHEET}" not found in ${input}`);

// Cells were pasted with hard line breaks and stray spaces; flatten them.
const clean = (v) => String(v ?? "").replace(/\s+/g, " ").trim();

const rows = XLSX.utils
  .sheet_to_json(sheet, { header: 1, blankrows: false })
  .filter((r) => clean(r[2]) && r[6] != null && clean(r[6]) !== "");

// The same topic is spelled a few ways ("Processing and" / "Processing, and",
// double spaces). Fold them together and keep the most common spelling.
const topicKey = (t) => clean(t).toLowerCase().replace(/[^a-z0-9]/g, "");
const spellings = new Map();
for (const r of rows) {
  const counts = spellings.get(topicKey(r[5])) ?? new Map();
  counts.set(clean(r[5]), (counts.get(clean(r[5])) ?? 0) + 1);
  spellings.set(topicKey(r[5]), counts);
}
const topicName = (t) =>
  [...spellings.get(topicKey(t))].sort((a, b) => b[1] - a[1])[0][0];

// Map preserves insertion order, i.e. the sheet's order.
const groups = new Map();
for (const r of rows) {
  const id = Number(r[6]);
  if (!groups.has(id)) groups.set(id, { id, topics: [], papers: [] });
  const slot = groups.get(id);
  const topic = topicName(r[5]);
  if (!slot.topics.includes(topic)) slot.topics.push(topic);
  slot.papers.push({
    id: Number(r[0]),
    title: clean(r[2]),
    authors: clean(r[1]),
    track: clean(r[3]),
    topic,
  });
}

const slots = [...groups.values()];
writeFileSync(
  output,
  `// GENERATED by scripts/build-slots.mjs from the "${SHEET}" sheet —
// do not edit by hand; re-run the script when the spreadsheet changes.
// Order of slots and of papers within a slot is the sheet's own order.
export const slots = ${JSON.stringify(slots, null, 2)};

export default slots;
`
);
console.log(
  `${slots.length} slots, ${rows.length} papers -> ${output}\n` +
    slots.map((s) => `  slot ${s.id}: ${s.papers.length}`).join("\n")
);
